export { default as SunAnimation } from './sun.json'
export { default as LunchAnimation } from './lunch.json'
export { default as MoonAnimation } from './moon.json'
export { default as NightAnimation } from './night.json'
export { default as WorkingAnimation } from './working.json'
