export { default as PlayArrowIcon } from '@material-ui/icons/PlayArrow'
export { default as PauseIcon } from '@material-ui/icons/Pause'
export { default as SettingsIcon } from '@material-ui/icons/Settings'
export { default as TimerIcon } from '@material-ui/icons/Timer'
export { default as SunIcon } from './sun.svg'
export { default as MoonIcon } from './moon.svg'
export { default as RedoIcon } from './redo.svg'
